// Result states from GensokyoClub/th08 (MIT).
#pragma once
namespace th08 {
enum ResultScreenState
{
    RESULT_SCREEN_STATE_INIT = 0,
    RESULT_SCREEN_STATE_CHOOSING_CATEGORY = 1,
    RESULT_SCREEN_STATE_EXITING = 2,
    RESULT_SCREEN_STATE_BEST_SCORES_CHOOSING_DIFFICULTY = 3,
    RESULT_SCREEN_STATE_BEST_SCORES_CHOOSING_CHARACTER = 4,
    RESULT_SCREEN_STATE_BEST_SCORES = 5,
    RESULT_SCREEN_STATE_SPELLCARDS_CHOOSING_DIFFICULTY = 6,
    RESULT_SCREEN_STATE_SPELLCARDS_CHOOSING_CHARACTER = 7,
    RESULT_SCREEN_STATE_SPELLCARDS = 8,
    RESULT_SCREEN_STATE_WRITING_HIGHSCORE_NAME = 9,
    RESULT_SCREEN_STATE_SAVE_REPLAY_QUESTION = 10,
    RESULT_SCREEN_STATE_CANT_SAVE_REPLAY = 11,
    RESULT_SCREEN_STATE_CHOOSING_REPLAY_FILE = 12,
    RESULT_SCREEN_STATE_WRITING_REPLAY_NAME = 13,
    RESULT_SCREEN_STATE_OVERWRITE_REPLAY_FILE = 14,
    RESULT_SCREEN_STATE_STATS_SCREEN = 15,
    RESULT_SCREEN_STATE_STATS_TO_SAVE_TRANSITION = 16,
    RESULT_SCREEN_STATE_PRACTICE = 17,
    RESULT_SCREEN_STATE_SCORE_SAVE = 18,
    RESULT_SCREEN_STATE_OTHER_STATS_SCREEN_INIT = 19,
    RESULT_SCREEN_STATE_OTHER_STATS_SCREEN = 20,
    RESULT_SCREEN_STATE_OTHER_STATS_TO_INIT_TRANSITION = 21,
    RESULT_SCREEN_STATE_SPELL_PRACTICE = 22,
};

enum ResultScreenAction
{
    RESULT_SCREEN_ACTION_TITLESCREEN,
    RESULT_SCREEN_ACTION_GAME_RESULTS,
    RESULT_SCREEN_ACTION_SAVE_SCORE
};

}
