#ifdef TH_NATIVE_PLATFORM
// Switch port of th08_web/cpp/sdl/FontHost.cpp: SDL3_ttf -> SDL2_ttf.
// msgothic.ttc next to th08.dat, else the Switch's built-in Japanese font.
// cp932.bin / blend.bin come from <data>/fonts/ when present (the upstream
// GDI-derived tables), otherwise they are generated here.
#include "PlatformHost.hpp"
#include "Platform.hpp"
#include <SDL.h>
#include <SDL_ttf.h>
#include <algorithm>
#include <cmath>
#include <set>
#ifdef __SWITCH__
#include <switch.h>
#endif
namespace th08 {
namespace {std::map<std::pair<i32,i32>,TTF_Font*> faces;bool started=false;
#include "cp932_table.inc" // generated by scripts/gen_cp932.py: cp932_map[65536]
TTF_Font* open_font(i32 height){
    const auto path=host::paths().data_file("msgothic.ttc");
    if(host::exists(path))return TTF_OpenFont(path.c_str(),height);
#ifdef __SWITCH__
    static bool tried=false;static PlFontData shared{};
    if(!tried){tried=true;if(R_FAILED(plInitialize(PlServiceType_User))||R_FAILED(plGetSharedFontByType(&shared,PlSharedFontType_Standard)))shared.address=nullptr;}
    if(shared.address)return TTF_OpenFontRW(SDL_RWFromConstMem(shared.address,int(shared.size)),1,height);
    return nullptr;
#else
    for(const char* c:{"/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc","/usr/share/fonts/truetype/fonts-japanese-gothic.ttf"})if(host::exists(c))return TTF_OpenFont(c,height);
    return nullptr;
#endif
}
}
bool sdl_glyph(i32 height,i32 weight,u16 code,JapaneseFont::Glyph& glyph,std::vector<u8>& pixels){
    if(!started){if(TTF_Init()!=0)return false;started=true;}
    auto& face=faces[{height,weight}];if(!face){face=open_font(height);if(!face)return false;
        TTF_SetFontKerning(face,0);TTF_SetFontHinting(face,TTF_HINTING_NORMAL);if(weight>=600)TTF_SetFontStyle(face,TTF_STYLE_BOLD);}
    int left,right,bottom,top,advance;
    if(TTF_GlyphMetrics32(face,code,&left,&right,&bottom,&top,&advance)!=0)return false;
    auto* image=TTF_RenderGlyph32_Blended(face,code,{255,255,255,255});if(!image)return false;
    auto* rgba=SDL_ConvertSurfaceFormat(image,SDL_PIXELFORMAT_RGBA32,0);SDL_FreeSurface(image);if(!rgba)return false;
    // SDL glyph surfaces already include the font's baseline placement. Switch
    // port: fonts other than MS Gothic (the system-font fallback) have taller
    // line metrics; drop the rows above MS Gothic's ascent (220/256 em) and keep
    // one em, MS Gothic's cell height.
    const i32 skip=std::clamp(TTF_FontAscent(face)-i32(std::lround(height*220.0/256.0)),0,rgba->h);const i32 rows=std::min(rgba->h-skip,height);
    glyph={code,0,i16(advance),0,0,u16(rgba->w),u16(rows)};pixels.resize(size_t(rgba->w)*rows);
    const auto* data=static_cast<const u8*>(rgba->pixels)+skip*rgba->pitch;for(int y=0;y<rows;y++)for(int x=0;x<rgba->w;x++)pixels[y*rgba->w+x]=(u32(data[y*rgba->pitch+x*4+3])*15+127)/255;
    SDL_FreeSurface(rgba);return true;
}
void sdl_fonts_shutdown(){for(auto& face:faces)TTF_CloseFont(face.second);faces.clear();if(started)TTF_Quit();started=false;}
bool BrowserRuntime::native_fonts(){
    const auto dir=host::paths().data_file("fonts");std::vector<u8> bytes;
    if(!sdl_read_file((dir+"/cp932.bin").c_str(),bytes)||bytes.size()!=131072){bytes.resize(131072);std::memcpy(bytes.data(),cp932_map,131072);}
    if(!put_font(0,bytes.data(),u32(bytes.size())))return false;
    if(!sdl_read_file((dir+"/blend.bin").c_str(),bytes)||bytes.size()!=131072){
        // [coverage 0..15][destination 5-bit channel][text 8-bit channel] ->
        // 5-bit result: coverage-weighted mix of the ARGB1555 target and text.
        bytes.resize(131072);
        for(u32 a=0;a<16;++a)for(u32 before=0;before<32;++before)for(u32 text=0;text<256;++text)
            bytes[a*8192+before*256+text]=u8(std::lround(before*(15.0-a)/15.0+text*31.0/255.0*a/15.0));
    }
    if(!put_font(1,bytes.data(),u32(bytes.size())))return false;
    if(!started){if(TTF_Init()!=0)return false;started=true;}
    if(auto* probe=open_font(16)){TTF_CloseFont(probe);return true;}
    host::log("No Japanese font: copy msgothic.ttc (from Windows) next to th08.dat");return false;}
u32 BrowserRuntime::native_font_steps(){
    if(warm_glyphs.empty()){std::set<u16> codes;for(u16 code=32;code<127;code++)codes.insert(code);
        const auto text=read("musiccmt.txt");const auto* p=text.data();const auto* end=p+text.size();while(p<end){const auto code=fonts.encoding.next(p,end);if(code>=32)codes.insert(code);}
        warm_glyphs.assign(codes.begin(),codes.end());}
    return (warm_glyphs.size()*4+15)/16;
}
bool BrowserRuntime::native_font_step(u32 step){
    const i32 profiles[][2]={{16,400},{16,600},{26,600},{28,600}};
    for(u32 i=step*16;i<std::min<u32>((step+1)*16,warm_glyphs.size()*4);i++){
        const auto* profile=profiles[i/warm_glyphs.size()];const auto* font=fonts.find(profile[0],profile[1]);if(!font)return false;
        if(!font->find(warm_glyphs[i%warm_glyphs.size()])&&!font->find(0x30fb))return false;
    }return true;
}
}
#endif
